#version: '3.8'
services:
  db:
    image: postgres:16-alpine
    container_name: emails-pgdb
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - db.env
    networks:
      - db-network

volumes:
  db:
    driver: local
networks:
  db-network: